
%script to train and test spectral model

ID = 30;

load(strcat('SpectralTainData', num2str(ID),'.mat'));

[rootTensor  ...
 tailTensor  ...
 obsTensor  ...
 tranTensor ...
 durTensor ] = learnSpectModel2(train(1:end,:), Nobs, Nhid_true, Dmin_true, Dmax_true, A1_true, A_true, D_true, O_true);

numObs = ceil( (log(Nhid_true)+log(Dmax_true)) / log(Nhid_true) );

result = testSpectModel2(test, Nobs, numObs, ...
                          rootTensor,  ...
                          tailTensor,  ...
                          obsTensor,  ...
                          tranTensor, ...
                          durTensor);
