function [rootTensor ...
          tailTensor ...
          obsTensors ...
          tranTensors ...
          durTensors] = learnSpectModel3(train, ...
                                        numObs, ...
                                        span, ...
                                        skip, ...
                                        obsDim, ...
                                        stateDim, ...
                                        durMin, ...
                                        durMax, A1_true, A_true, D_true, O_true)


%pick a data point inside a sequence to be a pivot
%pivot_ind = randi([start_ind end_ind], 1);

[L, N] = size(train);

%find start and end indeces in the data sequence, so that tensors can be
%estimated from enough data
tran_start_ind = span + 2;
tran_end_ind = N - span;

%duration clique should not go beyond transition clique (which is last)
dur_start_ind = span + 1;
dur_end_ind = N - span - 1;



%estimate root tensor
rootTensor = estimateRootTensor(train, ...
                                numObs,...
                                skip, ...
                                span, ...
                                obsDim,...
                                durMax, A1_true, A_true, D_true, O_true);

%estimate tail tensor
tailTensor = estimateTailTensor(train, ...
                                tran_end_ind, ...
                                numObs, ...
                                skip, ...
                                span, ...
                                obsDim, ...
                                stateDim, ...
                                durMin, ...
                                durMax, A1_true, A_true, D_true, O_true);

%estimate observation tensor
obsTensors = estObsTensor2(train, ...
                                tran_end_ind, ...
                                obsDim, ...
                                stateDim, A1_true, A_true, D_true, O_true);

%estimate transition tensor (-1 because last term will be TailTensor)
tranTensors = estTranTensor2(train, ...
                                  tran_start_ind:tran_end_ind-1, ...
                                  numObs, ...
                                  skip, ...
                                  span, ...
                                  obsDim, ...
                                  stateDim, ...
                                  durMin, ...
                                  durMax, A1_true, A_true, D_true, O_true);

%estimate duration tensor
durTensors = estDurTensor2(train, ...
                                dur_start_ind:dur_end_ind, ...
                                numObs, ...
                                skip, ...
                                span, ...
                                obsDim, ...
                                stateDim, ...
                                durMin, ...
                                durMax, A1_true, A_true, D_true, O_true);
