function [rootTensor ...
          tailTensor ...
          obsTensors ...
          tranTensors ...
          durTensors] = learnSpectModel(train, numObs, obsDim, stateDim, durMin, durMax)


%pick a data point inside a sequence to be a pivot
%pivot_ind = randi([start_ind end_ind], 1);

[L, N] = size(train);

%find start and end indeces in the data sequence, so that tensors can be
%estimated from enough data
tran_start_ind = numObs + durMin + 1;
tran_end_ind = N - numObs - durMax + 1;

%duration clique should not go beyond transition clique (which is last)
dur_start_ind = numObs + durMin + 1;
dur_end_ind = N - numObs - durMax + 1;



%estimate root tensor
rootTensor = estimateRootTensor(train, ...
                                numObs,...
                                obsDim,...
                                durMax);

%estimate tail tensor
tailTensor = estimateTailTensor(train, ...
                                tran_end_ind, ...
                                numObs, ...
                                obsDim, ...
                                stateDim, ...
                                durMin, ...
                                durMax);

%estimate observation tensor
obsTensors = estimateObsTensors(train, ...
                                tran_end_ind, ...
                                obsDim, ...
                                stateDim);

%estimate transition tensor (-1 because last term will be TailTensor)
tranTensors = estimateTranTensors(train, ...
                                  tran_start_ind:tran_end_ind-1, ...
                                  numObs, ...
                                  obsDim, ...
                                  stateDim, ...
                                  durMin, ...
                                  durMax);

%estimate duration tensor
durTensors = estimateDurTensors(train, ...
                                dur_start_ind:dur_end_ind, ...
                                numObs, ...
                                obsDim, ...
                                stateDim, ...
                                durMin, ...
                                durMax);
                            
                            







