COMPILER = g++
CCFLAGS = -O0 -g
INCLUDES = -I. -I/home/apparikh/spectral_MT/code/boost_1_52_0

secondnhhmm: second-nh-hmm.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o secondnhhmm second-nh-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

thirdnhhmm: third-nh-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o thirdnhhmm third-nh-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

thirdnhhmmcomp: third-nh-hmm-compressed.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o thirdnhhmmcomp third-nh-hmm-compressed.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

overlappingjtree: simulation-jtree6.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp TemplateJTree.cpp TemplateJTNode.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o overlappingjtree simulation-jtree6.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp TemplateJTree.cpp TemplateJTNode.cpp FastIndexer.cpp

factorialhmm: factorial-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp TemplateJTree.cpp TemplateJTNode.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o factorialhmm factorial-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp TemplateJTree.cpp TemplateJTNode.cpp FastIndexer.cpp

transliterationmain: transliteration-main-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o transmain transliteration-main-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

transliterationspectral: transliteration-spectral.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o transmain transliteration-spectral.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

splicemain: splice-main-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o splicemain splice-main-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

splicespectral: splice-spectral.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o splicespectral splice-spectral.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp

debug: second-nh-hmm.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp FastIndexer.cpp
	${COMPILER} ${INCLUDES} -o secondnhhmmdebug second-nh-hmm.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp Tensor

all: factorial-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp TemplateJTree.cpp TemplateJTNode.cpp FastIndexer.cpp
	${COMPILER} ${CCFLAGS} ${INCLUDES} -o factorialhmm factorial-hmm-all.cpp BayesianNetwork.cpp CPT.cpp JTNode.cpp JTree.cpp Matrix.cpp StatsLibrary.cpp TemplateBayesianNetwork.cpp tensor.cpp TensorCPT.cpp TensorJTNode.cpp TensorJTree.cpp TensorVarElim.cpp VectorPlus.cpp TemplateJTree.cpp TemplateJTNode.cpp FastIndexer.cpp

clean: 
	rm -rf *.o secondnhhmm overlappingjtree secondnhhmmdeb thirdnhhmm thirdnhhmmcomp splicemain factorialhmm splicespectral transmain

